-- ===================================
-- スロット分析アプリ DBスキーマ
-- ===================================

-- 日別実戦データ
create table if not exists daily_results (
  id bigint generated by default as identity primary key,
  play_date date not null,
  hall_name text not null,
  machine_name text not null,
  unit_no int not null,
  games int default 0,
  diff int default 0,
  bb int default 0,
  rb int default 0,
  source text,
  created_at timestamptz default now(),
  constraint unique_daily_result unique(play_date, hall_name, unit_no)
);

-- ホール配置マップ
create table if not exists hall_maps (
  id bigint generated by default as identity primary key,
  hall_name text not null,
  map_name text default 'main',
  row_no int not null,
  col_no int not null,
  unit_no int,
  area text,
  updated_at timestamptz default now(),
  constraint unique_map_cell unique(hall_name, map_name, row_no, col_no)
);

-- イベント管理
create table if not exists events (
  id bigint generated by default as identity primary key,
  play_date date not null,
  hall_name text not null,
  event_name text not null,
  memo text,
  created_at timestamptz default now(),
  constraint unique_event unique(play_date, hall_name, event_name)
);

-- インデックス作成（パフォーマンス向上）
create index if not exists idx_daily_results_date on daily_results(play_date desc);
create index if not exists idx_daily_results_hall on daily_results(hall_name);
create index if not exists idx_daily_results_unit on daily_results(unit_no);
create index if not exists idx_hall_maps_hall on hall_maps(hall_name, map_name);
create index if not exists idx_events_date on events(play_date desc);

-- Row Level Security有効化
alter table daily_results enable row level security;
alter table hall_maps enable row level security;
alter table events enable row level security;

-- 既存ポリシー削除
drop policy if exists "public daily read" on daily_results;
drop policy if exists "public daily write" on daily_results;
drop policy if exists "public map read" on hall_maps;
drop policy if exists "public map write" on hall_maps;
drop policy if exists "public events read" on events;
drop policy if exists "public events write" on events;

-- v1: 身内用全公開ポリシー（将来的に認証連動に切替）
create policy "public daily read" on daily_results 
  for select using (true);
  
create policy "public daily write" on daily_results 
  for all using (true) with check (true);

create policy "public map read" on hall_maps 
  for select using (true);
  
create policy "public map write" on hall_maps 
  for all using (true) with check (true);

create policy "public events read" on events 
  for select using (true);
  
create policy "public events write" on events 
  for all using (true) with check (true);

-- コメント追加
comment on table daily_results is '日別実戦データ。1台1日1レコード';
comment on table hall_maps is 'ホール配置マップ。行列で台番号を管理';
comment on table events is 'イベント管理。ホールごとのイベント日を記録';
