create table if not exists daily_results (
  id bigint generated by default as identity primary key,
  play_date date not null,
  hall_name text not null,
  machine_name text not null,
  unit_no int not null,
  games int default 0,
  diff int default 0,
  bb int default 0,
  rb int default 0,
  source text,
  created_at timestamptz default now(),
  unique(play_date, hall_name, unit_no)
);

create table if not exists hall_maps (
  id bigint generated by default as identity primary key,
  hall_name text not null,
  map_name text default 'main',
  row_no int not null,
  col_no int not null,
  unit_no int,
  area text,
  updated_at timestamptz default now(),
  unique(hall_name, map_name, row_no, col_no)
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  play_date date not null,
  hall_name text not null,
  event_name text not null,
  memo text,
  created_at timestamptz default now(),
  unique(play_date, hall_name, event_name)
);

alter table daily_results enable row level security;
alter table hall_maps enable row level security;
alter table events enable row level security;

-- 身内用v1: anonで読み書き可能。URLを広く公開する段階ではログイン/RLSに切替。
drop policy if exists "public daily read" on daily_results;
drop policy if exists "public daily write" on daily_results;
drop policy if exists "public map read" on hall_maps;
drop policy if exists "public map write" on hall_maps;
drop policy if exists "public events read" on events;
drop policy if exists "public events write" on events;
create policy "public daily read" on daily_results for select using (true);
create policy "public daily write" on daily_results for all using (true) with check (true);
create policy "public map read" on hall_maps for select using (true);
create policy "public map write" on hall_maps for all using (true) with check (true);
create policy "public events read" on events for select using (true);
create policy "public events write" on events for all using (true) with check (true);
